version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt

formats:
  - htmlzip
  - pdf
  - epub

# Build documentation in the 'docs' directory
# Read the Docs will automatically find the 'docs' directory
